# Generated by Django 5.0.7 on 2024-08-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaserequest',
            name='linkedin_profile',
            field=models.URLField(default='https://www.linkedin.com/in/default'),
            preserve_default=False,
        ),
    ]
